LASB-3091 - capital and equity
ministryofjustice/laa-crime-applications-adaptor pull request #149
Opened 2024-04-15 11:52 UTC by lkm0287

## What

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3091)

## Checklist

Before you ask people to review this PR:

- [ ] Tests should be passing: `./gradlew test`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase main`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2024-04-15 14:02 UTC, stone-dj requested changes
I have left some feedback, please take a look and let me know if you have any questions.

2024-04-16 09:29 UTC, JHunt16 commented on crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/InvestmentMapper.java
> +        if (Objects.isNull(investmentType)) {
I'm not sure if they can. The variable that is being checked in each part of the if-else is different. For example we have Investment.InvestmentType.PEP.equals..., Investment.InvestmentType.SHARE.equals... etc. Don't know if that can be handled in the same way in a switch? Similarly I can't see how we can do Objects.isNull in there as well.

Happy to dig further but my quick experimentation failed :)

2024-04-17 10:38 UTC, lkm0287 commented on crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/CapitalEquityMapper.java
> +                .getPremiumBondsTotalValue() instanceof Integer;
It's boxed type Integer.

        "premium_bonds_total_value":{
          "anyOf":[
            {
              "type":"null"
            },
            {
              "type":"integer"
            }
          ]
        }

2024-04-17 11:54 UTC, nittagr approved these changes

2024-04-17 11:57 UTC, merged